version: "2"
services:
  app:
    container_name: tesen_app
    restart: always
    build: .
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017
